### ISSUE TITLE
Modified websocket protocol

### ISSUE THREAD

**Issue by TNieminen** [noopkat/ms-bing-speech-service#26]
Hi!

Microsoft changed the protocol just recently to form

wss://westus.stt.speech.microsoft.com/speech/recognition/dictation/cognitiveservices/v1?cid=<ENDPOINTID>&format=simple&language=en-US&Ocp-Apim-Subscription-Key=<USERKEY>&X-ConnectionId=EE2F4DFD11C541A4AA40AAC459012B9B

from format:
wss://<ENDPOINTID>.api.cris.ai/speech/recognition/dictation/cognitiveservices/v1?format=simple&language=en-US&Ocp-Apim-Subscription-Key=<USERKEY>&X-ConnectionId=EE2F4DFD11C541A4AA40AAC459012B9B"

Just a heads up. I might have time to fix this properly and make a pull request, but wouldn't totally count on it! And thanks for coding this up, it has gone to good use. :)

**Comment by noopkat** [comment]
thank you for letting me know! Do you mean this is for all bing speech endpoints, not just custom speech?

**Comment by TNieminen** [comment]
No problem! As far as I know this affected only the custom speech.

**Comment by noopkat** [comment]
Hi @TNieminen 

Apologies for dropping the ball on this issue.

Since then, there's been a new official version of a NodeJS and browser supported SDK for the unified Microsoft Speech Services (formally Bing Speech Service). It does support the custom speech service (although it now falls under the unified speech service it still works in a very similar way). I'd recommend checking that out instead, if you still have need for a library such as this: https://github.com/Azure-Samples/cognitive-services-speech-sdk

Therefore I'll respectfully close this issue and will be deprecating / archive this repo 🙇‍♀ Thanks again for your contribution.
