### ISSUE TITLE
The sample code don't terminate after recognition.

### ISSUE THREAD

**Issue by hs7772667** [noopkat/ms-bing-speech-service#28]
Hi noopkat,
 
Thanks for this very useful library. I was trying out the async/await sample code to sendfile to my custom speech service and I got the recognized text of the audio back. But the process does not exit by itself, it stays alive even after the recognizer is stopped.

**Comment by noopkat** [comment]
Hi @hs7772667 thanks for reporting this issue. I did some investigation and fixed a pretty glaring bug to do with the recognizer's `stop` method. I've tested it on my end and it now exits the process as expected. I have published a new version with this patch. 

Feel free to reopen this issue if the problem still persists for you. Thanks again for reporting - it really helps to know when my stuff is broken so that a fix can be promptly implemented 😄 

![bitmoji](https://render.bitstrips.com/v2/cpanel/585b164a-2a8f-4a01-87a6-2186e9ad7eb1-8016a622-e09b-4505-8856-7726a074b1f9-v1.png?transparent=1&palette=1&width=246)
